#include<stdio.h>
#include<locale.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main(){
int i, firstterm=0, secondterm=1, result=0, sum;

    while(firstterm + secondterm<=4000000){
        result = firstterm + secondterm;
            if(result%2==0){
                sum+=result;
            }
        secondterm = firstterm;
        firstterm = result;
    }

    printf("The sum of the even-valued terms in Fibonacci sequence whose values do not exceed four million is %d.", sum);
}
